import { cafeImage, restaurantImage, hotelImage, dealImage, memberAvatar, CITY_IMAGES, unsplash } from "./images";

export const CONTENT = {
  Lisbon: {
    travelTips: ["Buy a Viva Viagem card for metro, trams and trains.", "Take tram 28 for a cheap city tour — go early to avoid crowds.", "Pastéis de nata are best warm at Manteigaria.", "Most locals speak English; a 'bom dia' goes a long way."],
    safetyTips: ["Stick to well-lit streets in Bairro Alto at night.", "Watch for pickpockets on trams 28 and 15.", "Use official taxis or Bolt/Uber after dark."],
    bestAreas: [{ name: "Alfama", note: "Charming lanes, Fado bars, river views." }, { name: "Príncipe Real", note: "Leafy squares, boutiques, great cafés." }, { name: "Baixa", note: "Central, walkable, ideal for first-timers." }],
    transport: "Walkable centre, iconic trams, two metro lines and trains to the beach at Cascais. E-scooters are everywhere.",
    cafes: [{ name: "Hello, Kristof", img: cafeImage(0, 500), rating: 4.8 }, { name: "Copenhagen Coffee Lab", img: cafeImage(1, 500), rating: 4.7 }, { name: "Fabrica Coffee Roasters", img: cafeImage(2, 500), rating: 4.9 }],
    restaurants: [{ name: "Cervejaria Ramiro", img: restaurantImage(0, 500), rating: 4.7 }, { name: "Taberna da Rua das Flores", img: restaurantImage(1, 500), rating: 4.8 }, { name: "A Cevicheria", img: restaurantImage(2, 500), rating: 4.6 }],
    hotels: [{ name: "Memmo Alfama", img: hotelImage(0, 500), rating: 4.8 }, { name: "The Independent Hostel", img: hotelImage(1, 500), rating: 4.6 }, { name: "Casa do Príncipe", img: hotelImage(2, 500), rating: 4.9 }],
    deals: [{ name: "Lisbon Stay 20% off", img: dealImage(0, 500), note: "Save 20%" }, { name: "Tram pass bundle", img: dealImage(1, 500), note: "3 days €15" }],
    reviews: [{ name: "Isabella Chen", avatar: memberAvatar("mock_4"), rating: 5, text: "Felt completely safe solo. The café culture is unreal." }, { name: "Maya Rivera", avatar: memberAvatar("mock_1"), rating: 5, text: "Sunset at Miradouro da Senhora do Monte — magic." }],
  },
  Bali: {
    travelTips: ["Rent a scooter only if you're experienced; otherwise use Gojek.", "Carry a reusable bottle — refill stations are common.", "Respect temple dress codes (sarong provided).", "Budget in cash; warungs are cash-only."],
    safetyTips: ["Download offline maps before remote day trips.", "Stick to flagged beaches; rips are common.", "Use registered ride apps at night."],
    bestAreas: [{ name: "Ubud", note: "Wellness, rice terraces and yoga." }, { name: "Canggu", note: "Surf, cafés and digital nomads." }, { name: "Seminyak", note: "Sunset bars and boutique stays." }],
    transport: "Scooters dominate; Gojek/Grab for cars. Traffic can be heavy — allow extra time.",
    cafes: [{ name: "Seniman Coffee", img: cafeImage(3, 500), rating: 4.8 }, { name: "Anomali Coffee", img: cafeImage(4, 500), rating: 4.6 }, { name: "Clear Café", img: cafeImage(5, 500), rating: 4.9 }],
    restaurants: [{ name: "Locavore", img: restaurantImage(3, 500), rating: 4.9 }, { name: "Hujan Locale", img: restaurantImage(4, 500), rating: 4.7 }, { name: "Sage", img: restaurantImage(5, 500), rating: 4.6 }],
    hotels: [{ name: "Bambu Indah", img: hotelImage(3, 500), rating: 4.9 }, { name: "Bali Hideaway", img: hotelImage(4, 500), rating: 4.7 }, { name: "The Yoga Barn Lodge", img: hotelImage(5, 500), rating: 4.6 }],
    deals: [{ name: "Bali Retreat Deal", img: dealImage(2, 500), note: "Save 15%" }, { name: "Surf package", img: dealImage(3, 500), note: "5 lessons €99" }],
    reviews: [{ name: "Ava Laurent", avatar: memberAvatar("mock_2"), rating: 5, text: "A month in Ubud reset me. So many women travelling solo here." }, { name: "Sophie Martin", avatar: memberAvatar("mock_3"), rating: 5, text: "Wellness scene is unmatched." }],
  },
  Tulum: {
    travelTips: ["Bring cash — many spots are cash-only.", "Rent a bike to explore the beach zone.", "Book cenotes early to avoid tour crowds.", "Reef-safe sunscreen only."],
    safetyTips: ["Stick to the beach road at night; travel in groups.", "Use registered taxis after dark.", "Keep valuables at your hotel."],
    bestAreas: [{ name: "Playa", note: "Beach clubs and sunset dinners." }, { name: "Pueblo", note: "Budget eats and local life." }, { name: "La Veleta", note: "Yoga studios and cafés." }],
    transport: "Bikes for the beach zone, taxis for town; ADO buses connect to Cancún airport.",
    cafes: [{ name: "Matcha Bar", img: cafeImage(6, 500), rating: 4.7 }, { name: "Raw Love", img: cafeImage(7, 500), rating: 4.8 }, { name: "Cetli", img: cafeImage(0, 500), rating: 4.6 }],
    restaurants: [{ name: "Hartwood", img: restaurantImage(6, 500), rating: 4.8 }, { name: "Gitano", img: restaurantImage(7, 500), rating: 4.6 }, { name: "Casa Jaguar", img: restaurantImage(0, 500), rating: 4.7 }],
    hotels: [{ name: "Habitas", img: hotelImage(6, 500), rating: 4.8 }, { name: "Sanará Hotels", img: hotelImage(7, 500), rating: 4.9 }, { name: "Nomade", img: hotelImage(0, 500), rating: 4.7 }],
    deals: [{ name: "Cenote day pass", img: dealImage(0, 500), note: "2-for-1" }, { name: "Yoga retreat week", img: dealImage(1, 500), note: "Save 20%" }],
    reviews: [{ name: "Emma Thompson", avatar: memberAvatar("mock_5"), rating: 5, text: "Sunrise yoga and cenotes — pure reset." }, { name: "Sophie Martin", avatar: memberAvatar("mock_3"), rating: 4, text: "Beautiful but bring cash." }],
  },
  "Cape Town": {
    travelTips: ["Use the MyCiTi bus for the city and Atlantic seaboard.", "Hike Lion's Head in a group at sunrise.", "Try a township tour with a local guide.", "Tip 10–15% at restaurants."],
    safetyTips: ["Don't walk alone at night; use ride apps.", "Keep phones tucked away in crowds.", "Drive the Garden Route in daylight."],
    bestAreas: [{ name: "De Waterkant", note: "Stylish, walkable, central." }, { name: "Camps Bay", note: "Beach and sunset bars." }, { name: "Bo-Kaap", note: "Colourful, cultural, photogenic." }],
    transport: "Uber/Bolt are cheap and safe; MyCiTi buses for the seaboard; rent a car for the peninsula.",
    cafes: [{ name: "Truth Coffee", img: cafeImage(1, 500), rating: 4.8 }, { name: "Hard Pressed", img: cafeImage(2, 500), rating: 4.6 }, { name: "Bootlegger", img: cafeImage(3, 500), rating: 4.7 }],
    restaurants: [{ name: "The Test Kitchen", img: restaurantImage(1, 500), rating: 4.9 }, { name: "Kloof Street House", img: restaurantImage(2, 500), rating: 4.7 }, { name: "Mzansi", img: restaurantImage(3, 500), rating: 4.8 }],
    hotels: [{ name: "The Silo", img: hotelImage(1, 500), rating: 4.9 }, { name: "Camps Bay Retreat", img: hotelImage(2, 500), rating: 4.7 }, { name: "The Daddy Long Legs", img: hotelImage(3, 500), rating: 4.6 }],
    deals: [{ name: "Table Mountain cableway", img: dealImage(2, 500), note: "Sunset 25% off" }, { name: "Wine tour day", img: dealImage(3, 500), note: "€59" }],
    reviews: [{ name: "Sophie Martin", avatar: memberAvatar("mock_3"), rating: 5, text: "Mountains, ocean, wine — everything in one city." }, { name: "Isabella Chen", avatar: memberAvatar("mock_4"), rating: 5, text: "Felt safe with ride apps; hike in groups." }],
  },
  Copenhagen: {
    travelTips: ["Bike everywhere — most rentals include a lock.", "Get a Copenhagen Card for museums and transport.", "Tipping is included; round up if you like.", "Supermarkets (Irma) are great for budget lunches."],
    safetyTips: ["One of the safest cities globally — still watch bikes!", "Keep to bike lanes only if walking.", "Night buses run all night on weekends."],
    bestAreas: [{ name: "Nørrebro", note: "Cool cafés, young vibe." }, { name: "Vesterbro", note: "Design shops, food markets." }, { name: "Indre By", note: "Centre, canals, Tivoli." }],
    transport: "Bikes, metro (24/7) and S-trains. The harbour buses are a scenic way across.",
    cafes: [{ name: "Café Norden", img: cafeImage(4, 500), rating: 4.9 }, { name: "Democratic Coffee", img: cafeImage(5, 500), rating: 4.7 }, { name: "Coffee Collective", img: cafeImage(6, 500), rating: 4.8 }],
    restaurants: [{ name: "Torvehallerne", img: restaurantImage(4, 500), rating: 4.7 }, { name: "Smørrebrød at Schønnemann", img: restaurantImage(5, 500), rating: 4.8 }, { name: "Releve", img: restaurantImage(6, 500), rating: 4.7 }],
    hotels: [{ name: "Hotel Sanders", img: hotelImage(4, 500), rating: 4.9 }, { name: "Cph Studio Hotel", img: hotelImage(5, 500), rating: 4.6 }, { name: "Wakeup Copenhagen", img: hotelImage(6, 500), rating: 4.5 }],
    deals: [{ name: "Canal tour", img: dealImage(0, 500), note: "Save 15%" }, { name: "Museum pass", img: dealImage(1, 500), note: "3 days €35" }],
    reviews: [{ name: "Ava Laurent", avatar: memberAvatar("mock_2"), rating: 5, text: "Hygge is real. Biking along the canals every morning." }, { name: "Maya Rivera", avatar: memberAvatar("mock_1"), rating: 4, text: "Pricey but worth it." }],
  },
  Paris: {
    travelTips: ["Buy a Navigo Easy for metro day passes.", "Picnic at Canal Saint-Martin, not the Champs.", "Free museum first Sundays.", "Greet with 'Bonjour' before asking anything."],
    safetyTips: ["Watch for pickpockets at Sacré-Cœur and on the RER.", "Keep bags zipped in tourist crowds.", "Stick to lit métro stations at night."],
    bestAreas: [{ name: "Le Marais", note: "Boutiques, cafés, central." }, { name: "Canal Saint-Martin", note: "Local, relaxed, picnic spots." }, { name: "Montmartre", note: "Views and charm — mind pickpockets." }],
    transport: "Métro everywhere; walk the centre; Velib bikes for riverside rides.",
    cafes: [{ name: "Café de Flore", img: cafeImage(7, 500), rating: 4.6 }, { name: "Boot Café", img: cafeImage(0, 500), rating: 4.7 }, { name: "Fragments", img: cafeImage(1, 500), rating: 4.8 }],
    restaurants: [{ name: "Olive & Vine", img: restaurantImage(7, 500), rating: 4.7 }, { name: "Chez Janou", img: restaurantImage(0, 500), rating: 4.6 }, { name: "Bouillon Pigalle", img: restaurantImage(1, 500), rating: 4.7 }],
    hotels: [{ name: "Maison du Parc", img: hotelImage(7, 500), rating: 4.8 }, { name: "Hôtel Providence", img: hotelImage(0, 500), rating: 4.7 }, { name: "Generator Paris", img: hotelImage(1, 500), rating: 4.5 }],
    deals: [{ name: "Paris Dinner 2-for-1", img: dealImage(2, 500), note: "2-for-1" }, { name: "Museum pass", img: dealImage(3, 500), note: "Save 20%" }],
    reviews: [{ name: "Isabella Chen", avatar: memberAvatar("mock_4"), rating: 5, text: "Golden hour along the Seine never gets old." }, { name: "Emma Thompson", avatar: memberAvatar("mock_5"), rating: 5, text: "My favourite city for a girls' trip." }],
  },
  Marrakech: {
    travelTips: ["Stay in a riad inside the medina for the full experience.", "Haggle — start at 30% of asking.", "Dress modestly; cover shoulders and knees.", "Carry small dirham notes for tips."],
    safetyTips: ["Walk with confidence; ignore touts offering 'directions'.", "Use registered taxis; insist on the meter.", "Travel in pairs in the souks at night."],
    bestAreas: [{ name: "Medina", note: "Riads, souks, atmosphere." }, { name: "Gueliz", note: "Modern, cafés, galleries." }, { name: "Palmeraie", note: "Quiet retreats and spas." }],
    transport: "Walk the medina, petit taxis for the city; day trips by private driver.",
    cafes: [{ name: "Café des Épices", img: cafeImage(2, 500), rating: 4.7 }, { name: "Nomad", img: cafeImage(3, 500), rating: 4.8 }, { name: "Le Jardin", img: cafeImage(4, 500), rating: 4.6 }],
    restaurants: [{ name: "Saffron Table", img: restaurantImage(2, 500), rating: 4.7 }, { name: "Dar Yacout", img: restaurantImage(3, 500), rating: 4.6 }, { name: "Nobu Marrakech", img: restaurantImage(4, 500), rating: 4.7 }],
    hotels: [{ name: "El Fenn", img: hotelImage(2, 500), rating: 4.9 }, { name: "Riad Mena", img: hotelImage(3, 500), rating: 4.8 }, { name: "La Mamounia", img: hotelImage(4, 500), rating: 4.9 }],
    deals: [{ name: "Marrakech Spa 30% off", img: dealImage(0, 500), note: "Save 30%" }, { name: "Desert day trip", img: dealImage(1, 500), note: "€49" }],
    reviews: [{ name: "Maya Rivera", avatar: memberAvatar("mock_1"), rating: 5, text: "The riads and hammams were dreamy." }, { name: "Emma Thompson", avatar: memberAvatar("mock_5"), rating: 4, text: "Magical but busy — book a guided souk walk." }],
  },
  Tokyo: {
    travelTips: ["Get a Suica card for trains.", "Conbini (7-Eleven) food is genuinely great.", "Carry cash — small places are cash-only.", "Stand on the left on escalators (Tokyo)."],
    safetyTips: ["One of the safest cities anywhere — walk freely at night.", "Keep quiet on trains; no calls.", "Note your station number if you get lost."],
    bestAreas: [{ name: "Shimokitazawa", note: "Vintage, cafés, indie vibe." }, { name: "Shibuya", note: "Crossing, shopping, energy." }, { name: "Asakusa", note: "Temples, old-town feel." }],
    transport: "JR Yamanote loop + subway; Suica tap-and-go; trains until ~1am.",
    cafes: [{ name: "Onibus Coffee", img: cafeImage(5, 500), rating: 4.8 }, { name: "Bear Pond Espresso", img: cafeImage(6, 500), rating: 4.7 }, { name: "Fuglen", img: cafeImage(7, 500), rating: 4.6 }],
    restaurants: [{ name: "Ichiran Ramen", img: restaurantImage(5, 500), rating: 4.7 }, { name: "Sushi Saito", img: restaurantImage(6, 500), rating: 4.9 }, { name: "Tsukiji outer market", img: restaurantImage(7, 500), rating: 4.6 }],
    hotels: [{ name: "Park Hyatt Tokyo", img: hotelImage(5, 500), rating: 4.9 }, { name: "Mustard Hotel", img: hotelImage(6, 500), rating: 4.6 }, { name: "Onsen Ryokan", img: hotelImage(7, 500), rating: 4.8 }],
    deals: [{ name: "Tokyo Metro 24h", img: dealImage(2, 500), note: "€6/day" }, { name: "Ryokan stay", img: dealImage(3, 500), note: "Save 15%" }],
    reviews: [{ name: "Sophie Martin", avatar: memberAvatar("mock_3"), rating: 5, text: "Safest solo trip I've ever taken." }, { name: "Emma Thompson", avatar: memberAvatar("mock_5"), rating: 5, text: "Shimokitazawa cafés are the best." }],
  },
};

export function contentFor(city) {
  return CONTENT[city] || CONTENT["Lisbon"];
}