import { hotelImage, galleryFromPool } from "@/lib/images";

export const HOTELS = [
  {
    name: "Memmo Alfama", city: "Lisbon", country: "Portugal", image: hotelImage(0),
    stars: 4, memberRating: 4.8, reviews: 142, pricePerNight: 180, distance: 0.5,
    tags: { pool: false, gym: true, spa: false, breakfast: true, beach: false, cityCenter: true, solo: true, womenReviews: true },
    address: "Travessa do Outeirinho 11, 1100-453 Lisboa", website: "https://memmoalfama.pt", bookingUrl: "https://booking.com/memmo-alfama",
    gallery: galleryFromPool(hotelImage, 3, 10),
    description: "A boutique hideaway in the heart of Alfama with rooftop pool, river views and calm courtyards. Ideal for solo travellers.",
    safetyNote: "Quiet, well-lit hillside streets; reception is staffed 24/7.",
    locationNote: "Steps from Miradouro das Portas do Sol; walkable to most sights.",
  },
  {
    name: "Habitas Tulum", city: "Tulum", country: "Mexico", image: hotelImage(1),
    stars: 5, memberRating: 4.7, reviews: 203, pricePerNight: 320, distance: 2.1,
    tags: { pool: true, gym: true, spa: true, breakfast: true, beach: true, cityCenter: false, solo: true, womenReviews: true },
    address: "Carretera Tulum Boca Paila Km 7.5, 77780 Tulum", website: "https://habitas.com/tulum", bookingUrl: "https://habitas.com/tulum/book",
    gallery: galleryFromPool(hotelImage, 3, 13),
    description: "Beachfront wellness retreat with yoga, sound baths and farm-to-table dining. Cabanas, spa and a strong solo-traveller community.",
    safetyNote: "Beach road is remote — use hotel-arranged transport at night.",
    locationNote: "On the beach zone; a bike to reach the pueblo.",
  },
  {
    name: "The Silo", city: "Cape Town", country: "South Africa", image: hotelImage(2),
    stars: 5, memberRating: 4.9, reviews: 176, pricePerNight: 410, distance: 0.4,
    tags: { pool: true, gym: true, spa: true, breakfast: true, beach: false, cityCenter: true, solo: true, womenReviews: true },
    address: "Silo District, V&A Waterfront, Cape Town", website: "https://thesilohotel.co.za", bookingUrl: "https://thesilohotel.co.za/book",
    gallery: galleryFromPool(hotelImage, 3, 16),
    description: "Iconic grain-silo conversion with panoramic harbour views, a rooftop pool and a world-class spa. Walkable and secure area.",
    safetyNote: "Within the secure V&A precinct; 24-hour security and concierge.",
    locationNote: "Central to the Waterfront; 20 min to Camps Bay.",
  },
  {
    name: "Hotel Sanders", city: "Copenhagen", country: "Denmark", image: hotelImage(3),
    stars: 5, memberRating: 4.9, reviews: 121, pricePerNight: 360, distance: 0.6,
    tags: { pool: false, gym: true, spa: false, breakfast: true, beach: false, cityCenter: true, solo: true, womenReviews: true },
    address: "Magasinkade 6, 1014 København", website: "https://hotelsanders.com", bookingUrl: "https://hotelsanders.com/book",
    gallery: galleryFromPool(hotelImage, 3, 19),
    description: "A cozy-luxury townhouse with a roaring fireplace, garden courtyard and a warmly personal service. A sanctuary in the centre.",
    safetyNote: "Very safe, central district; staffed round the clock.",
    locationNote: "Steps from Nyhavn and the metro.",
  },
  {
    name: "Casa do Príncipe", city: "Lisbon", country: "Portugal", image: hotelImage(4),
    stars: 4, memberRating: 4.9, reviews: 64, pricePerNight: 240, distance: 0.8,
    tags: { pool: false, gym: false, spa: false, breakfast: true, beach: false, cityCenter: true, solo: true, womenReviews: true },
    address: "Travessa do Pasteleiro 5, 1200 Lisboa", website: "https://casadoprincipe.pt", bookingUrl: "https://casadoprincipe.pt/reserve",
    gallery: galleryFromPool(hotelImage, 3, 22),
    description: "An intimate 9-room boutique guesthouse in Príncipe Real. Hand-picked art, plush beds and a quiet, women-loved vibe.",
    safetyNote: "Quiet, leafy neighbourhood; safe to walk at night.",
    locationNote: "Minutes from Bairro Alto and the botanical garden.",
  },
  {
    name: "Bambu Indah", city: "Bali", country: "Indonesia", image: hotelImage(5),
    stars: 4, memberRating: 4.9, reviews: 189, pricePerNight: 280, distance: 1.6,
    tags: { pool: true, gym: false, spa: true, breakfast: true, beach: false, cityCenter: false, solo: true, womenReviews: true },
    address: "Jl. Campuhan, Ubud, Bali", website: "https://bambuindah.com", bookingUrl: "https://bambuindah.com/booking",
    gallery: galleryFromPool(hotelImage, 3, 25),
    description: "Antarctica-free eco-lodge of Javanese houses perched over a jungle river. Natural spring pools, spa and sunrise yoga.",
    safetyNote: "Set back from the road; staff assist with night transport.",
    locationNote: "Riverside outside central Ubud; 10 min by shuttle.",
  },
  {
    name: "Wakeup Copenhagen", city: "Copenhagen", country: "Denmark", image: hotelImage(6),
    stars: 3, memberRating: 4.5, reviews: 980, pricePerNight: 95, distance: 0.9,
    tags: { pool: false, gym: true, spa: false, breakfast: true, beach: false, cityCenter: true, solo: true, womenReviews: false },
    address: "Carsten Niebuhrs Gade 11, 1577 København", website: "https://wakeupcopenhagen.dk", bookingUrl: "https://wakeupcopenhagen.dk/book",
    gallery: galleryFromPool(hotelImage, 3, 28),
    description: "Sleek, budget-friendly design hotel near the harbour. Compact rooms, great breakfast and a safe, central base.",
    safetyNote: "Central and very safe; well-lit harbourfront walk.",
    locationNote: "5 min from Fisketorvet and the metro.",
  },
  {
    name: "Maison du Parc", city: "Paris", country: "France", image: hotelImage(7),
    stars: 4, memberRating: 4.8, reviews: 88, pricePerNight: 290, distance: 1.2,
    tags: { pool: false, gym: false, spa: false, breakfast: true, beach: false, cityCenter: true, solo: true, womenReviews: true },
    address: "11 Rue de l'Arcade, 75008 Paris", website: "https://maisonduparc.fr", bookingUrl: "https://maisonduparc.fr/reserve",
    gallery: galleryFromPool(hotelImage, 3, 31),
    description: "Charming boutique hotel near Parc Monceau with refined rooms and a warm welcome. Quiet and perfectly located.",
    safetyNote: "Smart, central 8th arr.; well-lit and busy at night.",
    locationNote: "Walkable to Champs-Élysées and Galeries Lafayette.",
  },
  {
    name: "El Fenn", city: "Marrakech", country: "Morocco", image: hotelImage(0),
    stars: 4, memberRating: 4.9, reviews: 132, pricePerNight: 260, distance: 0.3,
    tags: { pool: true, gym: false, spa: true, breakfast: true, beach: false, cityCenter: true, solo: true, womenReviews: true },
    address: "Derb Al Farnatchi 1, 44000 Marrakech", website: "https://elfenn.com", bookingUrl: "https://elfenn.com/book",
    gallery: galleryFromPool(hotelImage, 3, 34),
    description: "A sprawling riad of courtyards, rooftop pools and art. Hammam, spa and a much-loved women-traveller sanctuary.",
    safetyNote: "Inside the medina; staff escort guests to taxis at night.",
    locationNote: "Moments from Jemaa el-Fnaa and the souks.",
  },
  {
    name: "Park Hyatt Tokyo", city: "Tokyo", country: "Japan", image: hotelImage(1),
    stars: 5, memberRating: 4.8, reviews: 410, pricePerNight: 540, distance: 2.2,
    tags: { pool: true, gym: true, spa: true, breakfast: true, beach: false, cityCenter: false, solo: true, womenReviews: true },
    address: "3-7-1-2 Nishi-Shinjuku, Tokyo", website: "https://tokyo.park.hyatt.com", bookingUrl: "https://tokyo.park.hyatt.com/reserve",
    gallery: galleryFromPool(hotelImage, 3, 37),
    description: "High-rise sanctuary above Shinjuku with skyline pools, spa and the famed New York Grill. Effortless, quiet luxury.",
    safetyNote: "Tokyo is exceptionally safe; hotel staff assist 24/7.",
    locationNote: "Shinjuku; direct train from Narita and Haneda.",
  },
];

export const HOTEL_TAG_FILTERS = [
  { key: "pool", label: "Pool" },
  { key: "gym", label: "Gym" },
  { key: "spa", label: "Spa" },
  { key: "breakfast", label: "Breakfast" },
  { key: "beach", label: "Beach access", shortLabel: "Beach" },
  { key: "cityCenter", label: "City center", shortLabel: "City center" },
  { key: "solo", label: "Solo-friendly", shortLabel: "Solo" },
  { key: "womenReviews", label: "Women-friendly reviews", shortLabel: "Women reviews" },
];

export const STAR_OPTIONS = [1, 2, 3, 4, 5];
export const FACILITY_LABELS = {
  pool: "Pool", gym: "Gym", spa: "Spa", breakfast: "Breakfast", beach: "Beach access",
  cityCenter: "City center", solo: "Solo-friendly", womenReviews: "Women-friendly reviews",
};