import {
  cafeImage,
  restaurantImage,
  hotelImage,
  CITY_IMAGES,
  eventImageFor,
  dealImageFor,
} from '@/lib/images';

/** Demo saved items — titles/ids match real detail routes in the app */
export const MOCK_SAVED_ITEMS = [
  {
    id: 'mock_saved_1',
    type: 'cafe',
    item_key: 'cafe:Café Norden',
    title: 'Café Norden',
    location: 'Copenhagen',
    country: 'Denmark',
    image: cafeImage(0),
    info: 'Organic coffee & smørrebrød',
    rating: 4.9,
    price: '$$',
  },
  {
    id: 'mock_saved_2',
    type: 'cafe',
    item_key: 'cafe:The Tiny Cup',
    title: 'The Tiny Cup',
    location: 'Lisbon',
    country: 'Portugal',
    image: cafeImage(1),
    info: 'Specialty espresso bar',
    rating: 4.7,
    price: '$',
  },
  {
    id: 'mock_saved_3',
    type: 'restaurant',
    item_key: 'restaurant:Cervejaria Ramiro',
    title: 'Cervejaria Ramiro',
    location: 'Lisbon',
    country: 'Portugal',
    image: restaurantImage(0),
    info: 'Portuguese seafood',
    rating: 4.7,
    price: '$$$',
  },
  {
    id: 'mock_saved_4',
    type: 'hotel',
    item_key: 'hotel:Memmo Alfama',
    title: 'Memmo Alfama',
    location: 'Lisbon',
    country: 'Portugal',
    image: hotelImage(0),
    info: 'Rooftop pool · Alfama',
    rating: 4.8,
    price: '€180/night',
  },
  {
    id: 'mock_saved_5',
    type: 'destination',
    item_key: 'destination:Bali',
    title: 'Bali',
    location: 'Bali',
    country: 'Indonesia',
    image: CITY_IMAGES.bali,
    info: 'Wellness & beach retreats',
    rating: 4.8,
  },
  {
    id: 'mock_saved_6',
    type: 'event',
    item_key: 'event:event_mock_1',
    title: 'Sunset Yoga',
    location: 'Santorini',
    country: 'Greece',
    image: eventImageFor({ city: 'Santorini', category: 'wellness' }),
    info: 'Wellness meetup',
    date: '2026-08-10',
  },
  {
    id: 'mock_saved_7',
    type: 'event',
    item_key: 'event:event_mock_2',
    title: 'Sunset Dinner in Santorini',
    location: 'Santorini',
    country: 'Greece',
    image: eventImageFor({ city: 'Santorini', category: 'dinner' }),
    info: 'Group dinner',
    date: '2026-08-12',
  },
  {
    id: 'mock_saved_8',
    type: 'deal',
    item_key: 'deal:deal_mock_1',
    title: 'Lisbon Stay 20% off',
    location: 'Lisbon',
    country: 'Portugal',
    image: dealImageFor({ city: 'Lisbon', category: 'hotels', title: 'Lisbon Stay' }),
    info: 'Memmo Alfama',
    price: '20% off',
  },
  {
    id: 'mock_saved_9',
    type: 'deal',
    item_key: 'deal:deal_mock_3',
    title: 'Paris Dinner 2-for-1',
    location: 'Paris',
    country: 'France',
    image: dealImageFor({ city: 'Paris', category: 'restaurants', title: 'Paris Dinner' }),
    info: 'Olive & Vine',
    price: '2-for-1',
  },
];

/** Subset for share sheet mocks */
export const SHARE_MOCK_SAVED = MOCK_SAVED_ITEMS.slice(0, 3);
